### ISSUE TITLE
Alternative for rules YAML format

### ISSUE THREAD

**Issue by banditopazzo** [exein-io/pulsar#305]
[serde-yaml](https://github.com/dtolnay/serde-yaml) has been archived, so we have to replace it.

There are 2 options:
- replace it with something like [yaml-rust2](https://github.com/Ethiraric/yaml-rust2) keeping yaml syntax
- completely change the format to another format (for example TOML, etc.)

Honestly I am in favor of the second option, and in particular to TOML, because it's well supported.

**Comment by vadorovsky** [comment]
Yes, +1 for TOML from me.

**Comment by dommyrock** [comment]
What do you think about this TOML structure ?

For example I tried to convert this YAML example to TOML rule from pulsar repo:
https://github.com/exein-io/pulsar/blob/main/rules/credential_access/ssh_backdoor_log.yaml 

I mostly went with [TOML - Array of Tables](https://toml.io/en/v1.0.0#array-of-tables).

This is pretty readable in my opinion, but I'm not 100% sure how we would group nested SQL like statements into SQL like groups. 

```toml
[[rules]]
name = "SSH related file changes"
type = "FileOpened"
category = "credential_access"
severity = "high"
description = "Identifies a Secure Shell (SSH) client or server process creating or writing to a known SSH backdoor log file. Adversaries may modify SSH-related binaries for persistence or credential access via patching sensitive functions to enable unauthorized access or to log SSH credentials for exfiltration."

[[rules.query]]
field = "header.image"
op = "IN"
values = ["/usr/sbin/sshd", "/usr/bin/ssh"]

[[rules.query]]
field = "payload.filename"
op = "AND"

    [[rules.query.operands]]
    op = "OR"
    filter = "STARTS_WITH"
    values = ["~", "." ]

    [[rules.query.operands]]
    op = "OR"
    filter = "ENDS_WITH"
    values = ["~"]

    [[rules.query.operands]]
    op = "NOT_IN"
    values = [".cache", ".viminfo", ".bash_history", ".google_authenticator", ".jelenv", ".csvignore", ".rtreport"]

    [[rules.query.operands]]
    op = "OR"
    filter = "STARTS_WITH"
    values = ["/private/etc/", "/usr/share/", "/usr/include/", "/usr/local/include/", "/private/tmp/", "/private/var/tmp/", "/usr/tmp/", "/usr/share/man/", "/usr/local/share/"]

    [[rules.query.operands]]
    op = "OR"
    filter = "ENDS_WITH"
    values = [".in", ".out", ".ini", ".h", ".gz", ".so", ".sock", ".sync", ".0", ".1", ".2", ".3", ".4", ".5", ".6", ".7", ".8", ".9"]

    [[rules.query.operands]]
    op = "IN"
    values = [
        "/private/etc/ssh/.sshd_auth",
        "/usr/bin/ssd",
        "/private/var/opt/power",
        "/private/etc/ssh/ssh_known_hosts",
        "/private/var/html/lol",
        "/private/var/log/utmp",
        "/private/var/lib",
        "/var/run/sshd/sshd.pid",
        "/var/run/nscd/ns.pid",
        "/var/run/udev/ud.pid",
        "/var/run/udevd.pid"
    ]
```

I have also tried to model a simple parser for this rule here https://github.com/dommyrock/toml-engine-parser .
Not sure if you wanted to go in this direction or some other.

**Comment by banditopazzo** [comment]
hey, probably me and @vadorovsky were thinking more on something like this:

```toml
[[rules]]
name = "..."
type = "..."
category = "..."
severity = "..."
description = "..."
condition = "..."
```

just changing the format from yaml to toml.

we are waiting to finalize the fields because we have few other things ongoing, but for sure we want the condition in a human readable format, same or similar to the one we are using now
